### ISSUE TITLE
Why not GitHub Pages?

### ISSUE THREAD

**Issue by konklone** [citricsquid/httpstatuses#13]
Seems like you could cut your hosting costs and ditch the sponsorship by making this into a Jekyll site hosted in GitHub Pages.

**Comment by fordhurley** [comment]
Is anyone working on this? If not I'd be happy to make a start on it.

**Comment by citricsquid** [comment]
@fordhurley As far as I know there is nobody currently working on this, if you'd like to take a shot at this it would be very welcome! Thank you.

**Comment by dptole** [comment]
@citricsquid 
Not sure if this issue is dead but I did this <a href="http://dptole.github.io/httpstatus.es/" target="_blank">http://dptole.github.io/httpstatus.es/</a> while learning AngularJS.
Mind to check?
