### ISSUE TITLE
Switch from httpstatus.es to httpstatuses.com

### ISSUE THREAD

**Issue by citricsquid** [citricsquid/httpstatuses#29]
At present the domain httpstatus.es is the primary domain of the site, and httpstatuses.com is a 301 redirect to httpstatus.es. The httpstatus.es domain is *cute*, but [according to Google](https://support.google.com/webmasters/answer/1347922?hl=en) they don't consider `.es` to be generic, meaning there are some search engine disadvantages to running an international site on `.es`. Search engines are the majority source of traffic for the website.

Switching the domains around (`httpstatus.es/200 -> httpstatuses.com/200`) shouldn't have any negative consequences, and would just be a matter of adjusting the web server configuration and buying a new SSL certificate.

- [x] Purchase SSL certificate for httpstatuses.com
- [x] Set up httpstatus.es as a 301 redirect to httpstatuses.com
- [x] Change `httpstatus.es` to `httpstatuses.com` in templates etc.
- [x] Rename GitHub project to `httpstatuses.com` (or just `httpstatuses` -- the repository can be a useful place to reference status codes too, it's not essential to visit the website?)

---

To verify site works correctly upon switch, the following must be true:

- [x] [https://httpstatuses.com/200](https://httpstatuses.com/200) displays the 200 status code page
- [x] [httpstatuses.com/200](http://httpstatuses.com/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [www.httpstatuses.com/200](http://www.httpstatuses.com/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [https://www.httpstatuses.com/200](https://www.httpstatuses.com/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [httpstatus.es/200](http://httpstatus.es/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [www.httpstatus.es/200](http://www.httpstatus.es/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [https://httpstatus.es/200](https://httpstatus.es/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)
- [x] [https://www.httpstatus.es/200](https://www.httpstatus.es/200) redirects to [https://httpstatuses.com/200](https://httpstatuses.com/200)

**Comment by clone1018** [comment]
+1

**Comment by LukeHandle** [comment]
It's a sad day, but if it helps SEO, then I guess...
