### ISSUE TITLE
I'm a teapot status removed from Rails

### ISSUE THREAD

**Issue by hansottowirtz** [citricsquid/httpstatuses#42]
As status code 418 => "I'm A Teapot" was removed from Rack at https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L552, the Rails status symbol :i'm_a_teapot does not exist anymore. The new status to symbol code `message.downcase.gsub(/\s|-|'/, '_').to_sym` would have made it :i_m_a_teapot, by the way.

**Comment by citricsquid** [comment]
Thank you! Looks like it was removed [in this commit in November 2014](https://github.com/rack/rack/commit/be28c6a2ac152fe4adfbef71f3db9f4200df89e8), not long after it was added to httpstatuses.com. I'll remove it from the site.
